### ISSUE TITLE
Organism filter performance.  WDK ByValue reporter:  support backend distrubutions

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/WDK#14]
this is to improve performance of column filters.  do not push the full column data to the column tool plugin.  instead do the distribution in SQL (group by).

- [ ] Add check in byValue reporter to get raw distribution stream from Oracle (SQL group by) when attribute is not derived 
- [ ] (bookkeeping) Disable (not offer a column reporter)  all derived attribute (text , link and id attributes)

**Comment by aurreco-uga** [comment]
test : comparing live and qa the org filter
