### ISSUE TITLE
WDK Dataset Param: fix ordering so it doesn't generate slow SQL on large data sets

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/WDK#16]
upgrade the dataset param so that we write a column containing the original ordering number.  this will alleviate problem of generating very slow sql with large data sets

**Comment by ryanrdoherty** [comment]
Fixed in build 57 with new code and a DB migration/population that introduced the dataset_value_order column into userlogins5.dataset_values table.
