### ISSUE TITLE
user datasets: too many requests for user and their preferences slows down the page loading significantly

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/WDK#50]
<img width="1240" alt="Screen Shot 2022-09-23 at 8 19 37 AM" src="https://user-images.githubusercontent.com/16354313/191973080-63a714e3-6944-4ab5-837e-5c0e94e54de9.png">

slack from ryan:
We're fetching the user for every user dataset.  Also fetching the users the uds is shared with... for every share I think.  I will streamline.

**Comment by ryanrdoherty** [comment]
@aurreco-uga I think there was also a redmine for this, and I remember putting in a fix.  Is it fixed? If so, can you close?

**Comment by aurreco-uga** [comment]
assuming this got fixed
